// <auto-generated />
using System;
using CodeInsightAI.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CodeInsightAI.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.9");

            modelBuilder.Entity("CodeInsightAI.Domain.Entities.PullRequestReport", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Author")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseBranch")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DetectedPurpose")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HeadBranch")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HeadSha")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("PrNumber")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PrTitle")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PrUrl")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Recommendations")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReliabilityScore")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RepoName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RepoOwner")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Verdict")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("RepoOwner", "RepoName", "PrNumber");

                    b.ToTable("PullRequestReports");
                });

            modelBuilder.Entity("CodeInsightAI.Domain.Entities.PullRequestReport", b =>
                {
                    b.OwnsMany("CodeInsightAI.Domain.Entities.ReviewIssue", "Issues", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("INTEGER");

                            b1.Property<int>("Category")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("FilePath")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("LineContent")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("LineNumber")
                                .HasColumnType("INTEGER");

                            b1.Property<Guid>("PullRequestReportId")
                                .HasColumnType("TEXT");

                            b1.Property<string>("RefactoredCode")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<int>("Severity")
                                .HasColumnType("INTEGER");

                            b1.Property<string>("Suggestion")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.Property<string>("Title")
                                .IsRequired()
                                .HasColumnType("TEXT");

                            b1.HasKey("Id");

                            b1.HasIndex("PullRequestReportId");

                            b1.ToTable("PullRequestReportIssues", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("PullRequestReportId");
                        });

                    b.Navigation("Issues");
                });
#pragma warning restore 612, 618
        }
    }
}
